version: '3.8'
services:
  app:
    image: website-ac
    container_name: 'anacouto-website'
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
