version: "3.8"
services:
  app:
    image: anacouto-website
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true